### PR TITLE
s2: Loop implements Region interface

### PR DESCRIPTION
**Pull request by buckhx**
Also added a LoopFromDegrees function to make building loops easier. I did not do explicit tests in this repo, but the tests here https://github.com/buckhx/gofence/blob/master/geofence/fence_test.go passed.

### CODE REVIEW

**Comment by buckhx** [comment]
Can I see the Loop you're using? I don't think it will work if the first and last points of the loop are the same like you do with geojson or similar. I think it makes sense to add a check like (Loop).IsValid() for that because it was a snag I hit will implementing this.

I'll make some time in the next week or so to test the loops that the other test methods use.

**Comment by dsymonds** [comment]
Thanks, though we have a bunch of this stuff already in flight, just not published yet. Stand by.

**Comment by pcallewaert** [comment]
@dsymonds Any idea when it will be published? :) Any chance there is a region coverer in that publish for loops (not on RectBound, but on the shape itself)?

**Comment by FelixMartel** [comment]
For people people stumbling across this and in need of a quick solution, the RegionCoverer seems to work better using.
```go
func (l *Loop) IntersectsCell(c s2.Cell) bool {
	// if any of the cell's vertices is contained by the loop
	// they intersect
	for i := 0; i < 4; i++ {
		v := c.Vertex(i)
		if l.ContainsPoint(v) {
			return true
		}
	}
	// missing case from the above implementation
	// where the loop is fully contained by the cell
	for _, v := range l.Vertices() {
		if c.ContainsPoint(v) {
			return true
		}
	}

	return false
}
```

**Comment by dsymonds** [comment]
It's getting closer. A significant chunk of it should be published in the next fortnight or so.

**Comment by giulioungaretti** [comment]
@dsymonds  great news! thanks for the update

**Comment by buckhx** [comment]
@FelixMartel That makes sense why my FlatCoverer worked as expected, but the RegionCoverer didn't. In my case the zoom level was fixed and the cells and loops were similar in size so a single cell would not fully contain a loop and the edge crossing method worked for that.

I'd change the PR to reflect this, but it seems it will be defunct once the library gets updated any way. @akhenakh might be interested in this.

**Comment by akhenakh** [comment]
Yes, following this!
As you said it may be the explanation for the region coverer not working properly.
I have my tests ready to be fired :)

**Comment by akhenakh** [comment]
First tests show it works as expected, good loop region coverage compared to c++ so far. 👍 
Need more time to confirm this on a big number of loops.

**Comment by alkhatib** [comment]
Any updates on this?

**Comment by akhenakh** [comment]
I've a particular case where covering of a simple 4 points polygons fails with @FelixMartel implementation of IntersectsCell.
Any updates on this @dsymonds ?

```
48.84533874029372 2.4018003197157896
48.8453952264004 2.401886152667487
48.846507283622735 2.4002499620546587
48.84645785938342 2.4001533999884823
```
For a flat 18 level cover it should return 11 cells but only returned 5

**Comment by dsymonds** [comment]
@akhenakh: Sorry, some work is stuck in a backlog.

**Comment by akhenakh** [comment]
Thanks for your recent commits @dsymonds on the loops regions

For others using the code in this PR, you can now do it from master.

**Comment by dsymonds** [comment]
Credit for the heavy lifting goes to @rsned. I only did the code reviews and the exporting.

I'll close this PR since I believe it's redundant with f65fe01.

**Comment by giulioungaretti** [comment]
Great addition, can't wait to try it out! Thanks @dsymonds and @rsned !!!

**Pull request closed without merging**
