### PR TITLE
PolygonFromLoops for more than one loop

### PR DESCRIPTION
**Pull request by buth**
This pull request includes an implementation of PolygonFromLoops for more than one loop along with the required Loop and Polygon methods.

### CODE REVIEW

**Comment by dsymonds** [comment]
Thanks, but this isn't a port of the C++ code, and doesn't get it quite right. @rsned is working on multi-loop polygon support; stay tuned for that.

**Comment by buth** [comment]
Can you elaborate on what it doesn't get right?

**Comment by rsned** [comment]
It's based on a several years out of date version of the C++ code.

**Comment by buth** [comment]
In the absence of more recent C++ code (as your company will not make it public) and a working Go implementation thereof, isn't this better than nothing? It seems like you're turning down a working implementation that would be useful to the community for internal reasons.

**Comment by dsymonds** [comment]
Sorry if it seems that way, but it's not. We're turning it down because we have a more correct port in progress already. The full up-to-date C++ version is also on its way.

**Comment by buth** [comment]
Is there a timeline?

**Comment by buth** [comment]
Also, you're defining "more correct" as "more like the internal C++ implementation"?

**Comment by buth** [comment]
If there's an issue with this code, let's address it here.

**Comment by dsymonds** [comment]
No particular timeline, but over the next few weeks I hope.

It's both closer to the C++ implementation and also, I believe, more numerically correct, but I don't really want to go hunting for specific data inputs that would demonstrate that. I'd prefer to use that time to get our proper port released.

**Comment by buth** [comment]
That is to say, this is a port of C++ code, code that is not public. The criteria for code acceptability is how well it matches the original. This pull request is not numerically correct for reasons that can't be demonstrated. This isn't an encouraging way to run an open source project, IMHO.

**Comment by dsymonds** [comment]
Yes, I know. Sorry. This isn't a traditional open source project in that sense.

**Pull request closed without merging**
