### PR TITLE
Fix floating point failures seen on ppc64le

### PR DESCRIPTION
**Pull request by prashantkhoje**
Fixes test failures:
    - TestClosestEdgeQueryTrueDistanceLessThanChordAngleDistance (#88)
    - TestPointMeasuresPointArea (#87)
    - TestPredicatesRobustSignEqualities (#86)

### CODE REVIEW

**Comment by prashantkhoje** [comment]
@rsned, Who can help to review this pull request?

Thank you,
Prashant

**Comment by rsned** [comment]
Do you get any errors in matrix3x3_test when using PPC?

**Comment by prashantkhoje** [comment]
No, i don't get any errors in matrix3x3_test on PPC.

**Comment by prashantkhoje** [comment]
@ambujkumar3 fyi

**Comment by rsned** [comment]
Fixed with commit https://github.com/golang/geo/commit/eee77999540a2fdb7ae874772c14223ee75e6739

**Pull request closed without merging**
